apiVersion: v1
data:
  AUTH_TYPE: "{{ .Values.django.authType}}"
  {{ if eq .Values.django.authType "auth0" }}
  AUTH0_CLIENT_ID: "{{ .Values.django.auth0ClientId }}"
  AUTH0_DOMAIN: "{{ .Values.django.auth0Domain }}"
  {{ else if eq .Values.django.authType "authing" }}
  AUTHING_APP_ID: "{{ .Values.django.authingAppId }}"
  AUTHING_DOMAIN: "{{ .Values.django.authingDomain }}"
  {{- end }}
  CELERY_FLOWER_USER: "{{ .Values.flower.user }}"
  CELERY_FLOWER_PASSWORD: "{{ .Values.flower.password }}"
  DJANGO_LOG_LEVEL: "INFO"
  MODEL_SERVER: "{{ .Values.django.modelServer }}"
  MODEL_SERVERS: '{{ .Values.django.modelServers | toJson }}'
  MODEL_FAMILIES: '{{ .Values.django.modelFamilies | toJson }}'
  VECTOR_DB_CONTEXT: '{{ .Values.django.vectorDBContext }}'
  VECTOR_DB_TYPE: "{{ .Values.django.vectorDBType }}"
  {{- if .Values.django.openaiAPIKey }}
  OPENAI_API_KEY: "{{ .Values.django.openaiAPIKey }}"
  {{- end}}
  {{- if .Values.django.openaiProxy }}
  OPENAI_API_PROXY: "{{ .Values.django.openaiProxy }}"
  {{- end}}
  FEISHU_APP_ID: "{{ .Values.django.feishu.appID }}"
  FEISHU_APP_SECRET: "{{ .Values.django.feishu.appSecret }}"
  FEISHU_ENCRYPT_KEY: "{{ .Values.django.feishu.encryptKey }}"
  EMBEDDING_MODEL: "{{ .Values.django.embeddingModel }}"
  EMBEDDING_DEVICE: "{{ .Values.django.embeddingDevice }}"
  ENABLE_QA_GENERATOR: "{{ .Values.django.enableQAGenerator }}"
  ES_HOST: "{{ .Values.django.esHost }}"
  WHISPER_HOST: http://openai-whisper-asr-service:9000
  PADDLEOCR_HOST: http://paddleocr-hubserving-service:8866
kind: ConfigMap
metadata:
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
  name: kubechat-config
