version: '3'

volumes:
  deeprag_postgres_data: {}
  deeprag_qdrant_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./Dockerfile
    image: deeprag_django
    container_name: deeprag_django
    depends_on:
      - postgres
      - redis
      - qdrant
    volumes:
      - .:/app:z
      - ~/.cache:/root/.cache
    env_file:
      - .docker-env
    ports:
      - "8000:8000"
    command: /app/scripts/start-django.sh

  postgres:
    image: postgres:14
    container_name: deeprag_postgres
    volumes:
      - deeprag_postgres_data:/var/lib/postgresql/data
    env_file:
      - .docker-env

  redis:
    image: redis:6
    container_name: deeprag_redis

  qdrant:
    image: qdrant/qdrant
    container_name: deeprag_qdrant
    volumes:
      - deeprag_qdrant_data:/qdrant/storage

  celeryworker:
    <<: *django
    image: deeprag_django
    container_name: deeprag_celeryworker
    depends_on:
      - redis
      - postgres
      - qdrant
    volumes:
      - .:/app:z
      - ~/.cache:/root/.cache
      - ./resources:/Users/ziang/git/DeepRAG/resources
    ports: []
    command: /app/scripts/start-celery-worker.sh

  celerybeat:
    <<: *django
    image: deeprag_django
    container_name: deeprag_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /app/scripts/start-celery-beat.sh

  flower:
    <<: *django
    image: deeprag_django
    container_name: deeprag_flower
    ports:
      - "5555:5555"
    command: /app/scripts/start-celery-flower.sh