{{- range .Values.models }}
{{- $rangeItem := . -}}
{{- with $ }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llmserver.fullname" . }}-{{ $rangeItem.name }}
  labels:
    {{- include "llmserver.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ $rangeItem.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "llmserver.selectorLabels" . | nindent 6 }}
      chat.kubeblocks.io/model-name: {{ $rangeItem.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "llmserver.selectorLabels" . | nindent 8 }}
        chat.kubeblocks.io/model-name: {{ $rangeItem.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "llmserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /app/resources
              ln -s /data/models /app/resources
              uvicorn server.llmserver:app --host 0.0.0.0 --log-config uvicorn-log-config.yaml
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: LLM_MODEL
              value: {{ $rangeItem.name | quote}}
          resources:
            {{- toYaml $rangeItem.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml $rangeItem.nodeSelector | nindent 8 }}
      {{- with $rangeItem.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          hostPath:
            path: /data/kubechat

{{- end }}
{{- end }}
