
efsId: fs-000f009e5b2735fc4

models:
  - name: vicuna-13b
    replicaCount: 0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: chat.kubeblocks.io/model-name
                  operator: In
                  values:
                  - vicuna-13b
    resources:
      limits:
        nvidia.com/gpu: 1
  - name: internlm-chat-7b
    replicaCount: 1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: chat.kubeblocks.io/model-name
                  operator: In
                  values:
                    - internlm-chat-7b
                    - baichuan-13b
    resources:
      limits:
        nvidia.com/gpu: 1
  - name: chatglm2-6b
    replicaCount: 0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: chat.kubeblocks.io/model-name
                  operator: In
                  values:
                    - chatglm2-6b
    resources:
      limits:
        nvidia.com/gpu: 1
  - name: baichuan-13b
    replicaCount: 1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: chat.kubeblocks.io/model-name
                  operator: In
                  values:
                    - baichuan-13b
    resources:
      limits:
        nvidia.com/gpu: 1
