{{- if .Values.whisper.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openai-whisper-asr
spec:
  replicas: {{ index .Values "whisper" "replicaCount" }}
  selector:
    matchLabels:
      app: openai-whisper-asr
  template:
    metadata:
      labels:
        app: openai-whisper-asr
    spec:
      containers:
        - name: openai-whisper-asr
          image: "{{ .Values.image.whisper.repository }}:{{ .Values.image.whisper.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9000
          env:
            - name: ASR_MODEL
              value: large-v2
            - name: ASR_ENGINE
              value: faster_whisper
          {{- with .Values.whisper.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
