image:
  tag: v0.1.4-alpha.8

ingress:
  className: alb
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing

django:
  domainName: chat.kubeblocks.io
  replicaCount: 2
  embeddingModel: bge
  embeddingDevice: cuda
  authType: auth0
  auth0ClientId: "G6RuQZZNaDorHGUEOv7Mgq1COqfryTB2"
  auth0Domain: "kubechat.jp.auth0.com"
  openaiAPIKey: ""
  resources:
    limits:
      nvidia.com/gpu: "1"

celery-worker:
  replicaCount: 2